// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether to enable the access point
     */
    enabled: boolean;
    /**
     * Access point password (omit to keep current, empty string to clear)
     */
    password?: string;
    /**
     * Access point SSID
     */
    ssid: string;
};

export type AuthStatusResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * true if the request carries a valid session
     */
    authenticated: boolean;
    /**
     * true if an admin password is set
     */
    required: boolean;
};

export type CharacteristicDto = {
    decoder: string;
    kind: string;
    uuid: string;
};

export type ConfigDto = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * HCI device ID, e.g. hci0
     */
    bluetooth_adapter: string;
    display: DisplayDto;
    library: LibraryDto;
    /**
     * Logging verbosity; applied live
     */
    log_level: 'debug' | 'info' | 'warn' | 'error';
    mqtt: MqttDto;
    sensors: Array<SensorDto> | null;
    slideshow: SlideshowDto;
    updater: UpdaterDto;
    weather: WeatherDto;
};

export type ConfigMetaBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address_types: Array<string> | null;
    backends: Array<string> | null;
    /**
     * Decoder/parser names from the sensor registry
     */
    decoders: Array<string> | null;
    kinds: Array<string> | null;
    log_levels: Array<string> | null;
    sensor_types: Array<string> | null;
    units: Array<string> | null;
};

export type ConfigResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * HCI device ID, e.g. hci0
     */
    bluetooth_adapter: string;
    display: DisplayDto;
    library: LibraryDto;
    /**
     * Logging verbosity; applied live
     */
    log_level: 'debug' | 'info' | 'warn' | 'error';
    mqtt: MqttDto;
    restart_pending: boolean;
    sensors: Array<SensorDto> | null;
    slideshow: SlideshowDto;
    updater: UpdaterDto;
    weather: WeatherDto;
};

export type Cookie = {
    Domain: string;
    Expires: string;
    HttpOnly: boolean;
    MaxAge: number;
    Name: string;
    Partitioned: boolean;
    Path: string;
    Quoted: boolean;
    Raw: string;
    RawExpires: string;
    SameSite: number;
    Secure: boolean;
    Unparsed: Array<string> | null;
    Value: string;
};

export type DisplayDto = {
    backend: 'wlopm' | 'vcgencmd';
    /**
     * Idle duration before screen blanks, e.g. "20m"
     */
    blank_after: string;
    /**
     * Hide the clock and date block on the kiosk overlay
     */
    hide_clock_date: boolean;
    labels: KioskLabelsDto;
    /**
     * BCP-47 date/time locale for the kiosk clock, e.g. en-US
     */
    locale: string;
    /**
     * Wayland connector name, e.g. "HDMI-A-1" (wlopm only)
     */
    output: string;
    /**
     * Counter-clockwise screen rotation in degrees (wlopm only); applied live via wlr-randr
     */
    rotation: 0 | 90 | 180 | 270;
    /**
     * IANA timezone for the kiosk clock/date, e.g. Europe/Budapest; empty uses the browser timezone
     */
    timezone: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FaceBoxDto = {
    x0: number;
    x1: number;
    y0: number;
    y1: number;
};

export type ImageFocusOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    detected: boolean;
    faces: Array<FaceBoxDto> | null;
};

export type ImageItem = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Image filename
     */
    name: string;
};

export type ImagePayload = {
    names: Array<string> | null;
};

export type ImmichLibraryDto = {
    /**
     * Write-only; leave blank to keep current
     */
    share_password?: string;
    /**
     * true if a password is stored; set false on PUT to clear
     */
    share_password_set: boolean;
    share_url: string;
    sync_interval: string;
};

export type KioskLabels = {
    humidity: string;
    inside: string;
    outside: string;
};

export type KioskLabelsDto = {
    /**
     * Caption under the humidity reading; empty hides it
     */
    humidity: string;
    /**
     * Caption under the inside reading; empty hides it
     */
    inside: string;
    /**
     * Caption under the outside reading; empty hides it
     */
    outside: string;
};

export type KioskPayload = {
    auto_crop: boolean;
    blurred_fill: boolean;
    hide_clock_date: boolean;
    labels: KioskLabels;
    locale: string;
    max_crop_percent: number;
    sensors: Array<string> | null;
    timezone: string;
    version: string;
    weather: boolean;
    window: Window;
};

export type LibraryDto = {
    backend: 'fs' | 'immich';
    immich: ImmichLibraryDto;
};

export type LibraryResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Active library backend (fs or immich)
     */
    backend: string;
    /**
     * Sync status for remote backends
     */
    sync?: LibrarySync;
};

export type LibrarySync = {
    /**
     * Number of synced assets
     */
    asset_count: number;
    /**
     * Error from last sync attempt
     */
    last_error?: string;
    /**
     * Timestamp of last successful sync
     */
    last_sync?: string;
};

export type LoginRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    password: string;
};

export type MockReadingDto = {
    delta: number;
    kind: string;
    value: number;
};

export type MqttBridgeDto = {
    base_topic: string;
    discovery_prefix: string;
    enabled: boolean;
    node_id: string;
    stale_after: string;
};

export type MqttDto = {
    bridge: MqttBridgeDto;
    broker: string;
    client_id: string;
    /**
     * Write-only; leave blank to keep current
     */
    password?: string;
    /**
     * true if a password is stored; set false on PUT to clear
     */
    password_set: boolean;
    username: string;
};

export type PingEvent = {
    [key: string]: never;
};

export type PutConfigResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    restart_pending: boolean;
};

export type ReadyEvent = {
    [key: string]: never;
};

export type ScreenAspectPayload = {
    aspect: number;
};

export type ScreenPayload = {
    auto: boolean;
    on: boolean;
};

export type ScreenStateResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether automatic power management is active
     */
    auto: boolean;
    /**
     * Current screen power state
     */
    state: 'on' | 'off';
};

export type SensorDto = {
    address_type?: 'random' | 'public';
    characteristics?: Array<CharacteristicDto> | null;
    id: string;
    json_field?: string;
    kind?: string;
    mac?: string;
    mock_readings?: Array<MockReadingDto> | null;
    parser?: string;
    poll_interval?: string;
    reset_after?: string;
    role: string;
    topic?: string;
    type: 'ble' | 'mqtt-subscriber' | 'mock';
};

export type SensorPayload = {
    device_id: string;
    kind: string;
    role?: string;
    timestamp: string;
    value: number;
};

export type SetImageOrderInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Apply the order to the running slideshow now (sent on Done)
     */
    commit?: boolean;
    /**
     * Full ordered list of image filenames
     */
    names: Array<string> | null;
};

export type SetPasswordRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Current password; required when one is already set
     */
    current?: string;
    /**
     * New password; empty disables protection
     */
    new: string;
};

export type SetScreenRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Desired screen power state
     */
    state: 'on' | 'off';
};

export type SlideshowDto = {
    /**
     * Shift the crop window within Window's bounds to keep detected faces in frame, reducing blur margin
     */
    auto_crop: boolean;
    /**
     * Show each photo at its full aspect ratio with a blurred, scaled copy of itself filling the gap instead of cropping
     */
    blurred_fill: boolean;
    images_dir: string;
    /**
     * Image advance interval, e.g. "2m"
     */
    interval: string;
    /**
     * Cap on how far auto_crop may zoom in past the no-crop fit, as a percent of that fit's scale
     */
    max_crop_percent: number;
    randomize: boolean;
    /**
     * Pair mismatched-orientation photos side-by-side
     */
    split_screen: boolean;
    /**
     * Insets the sharp foreground photo from its pane's edges (blurred_fill only); the blur still fills the full pane
     */
    window: WindowDto;
};

export type SystemDevicesBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * HCI device IDs, e.g. hci0
     */
    bluetooth_adapters: Array<string> | null;
    /**
     * Connected display connectors, e.g. HDMI-A-1
     */
    display_outputs: Array<string> | null;
    /**
     * true when the display backend can rotate and wlr-randr is installed
     */
    rotation_supported: boolean;
};

export type SystemInfoBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Host power-off is permitted (polkit rule present)
     */
    canPowerOff: boolean;
    /**
     * Host reboot is permitted (polkit rule present)
     */
    canReboot: boolean;
    /**
     * CPU temperature in Celsius
     */
    cpuTempC?: number;
    /**
     * OS hostname
     */
    hostname: string;
    /**
     * Primary non-loopback IPv4, empty if none
     */
    ip: string;
    /**
     * Used memory percent
     */
    memUsedPct?: number;
    /**
     * Build target, e.g. linux_armv6
     */
    platform: string;
    /**
     * System uptime since boot as a Go duration
     */
    systemUptime?: string;
    /**
     * True if undervoltage detected
     */
    undervoltage?: boolean;
    /**
     * Process uptime as a Go duration, e.g. 3h12m0s
     */
    uptime: string;
    /**
     * Build version
     */
    version: string;
};

export type TouchPayload = {
    at: string;
};

export type UpdateStatusResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether a newer version is available
     */
    available: boolean;
    /**
     * Running version
     */
    current: string;
    /**
     * RFC3339 time of the last check
     */
    last_check?: string;
    /**
     * False when the last check couldn't reach the release source
     */
    last_check_ok: boolean;
    /**
     * Outcome of the last apply, e.g. 'rolled back from v1.2.0'
     */
    last_result?: string;
    /**
     * Bumps each time a result is recorded; lets the UI detect a repeated outcome
     */
    last_result_seq?: number;
    /**
     * Newest available version
     */
    latest?: string;
    /**
     * Release notes page for the newest version
     */
    notes_url?: string;
    /**
     * Current updater activity
     */
    phase: 'idle' | 'checking' | 'downloading' | 'verifying' | 'applying';
    /**
     * Build target, e.g. linux_armv6
     */
    platform: string;
};

export type UpdaterDto = {
    auto_update: boolean;
    github_repo: string;
    /**
     * Write-only; leave blank to keep current
     */
    github_token?: string;
    /**
     * true if a token is stored; set false on PUT to clear
     */
    github_token_set: boolean;
    update_hour: number;
};

export type WeatherDto = {
    /**
     * Write-only; leave blank to keep current
     */
    api_key?: string;
    /**
     * true if an API key is stored; set false on PUT to clear
     */
    api_key_set: boolean;
    lat: number;
    lon: number;
    poll_interval: string;
    retry_interval: string;
    units: 'standard' | 'metric' | 'imperial';
};

export type WeatherPayload = {
    humidity: number;
    icon_code: string;
    temp: number;
};

export type WiFiConnectRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether the network is hidden (non-broadcasting)
     */
    hidden?: boolean;
    /**
     * Network password
     */
    password?: string;
    /**
     * Network SSID to connect to
     */
    ssid: string;
};

export type WiFiNetwork = {
    hidden: boolean;
    known: boolean;
    security: string;
    signal: number;
    ssid: string;
};

export type WiFiState = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ap_enabled: boolean;
    ap_has_password: boolean;
    ap_ssid: string;
    hostname: string;
    ip: string;
    last_connect_error?: string;
    last_connect_ssid?: string;
    mode: string;
    security: string;
    signal: number;
    ssid: string;
};

export type Window = {
    bottom: number;
    left: number;
    right: number;
    top: number;
};

export type WindowDto = {
    bottom: number;
    left: number;
    right: number;
    top: number;
};

export type ApRequestWritable = {
    /**
     * Whether to enable the access point
     */
    enabled: boolean;
    /**
     * Access point password (omit to keep current, empty string to clear)
     */
    password?: string;
    /**
     * Access point SSID
     */
    ssid: string;
};

export type AuthStatusResponseWritable = {
    /**
     * true if the request carries a valid session
     */
    authenticated: boolean;
    /**
     * true if an admin password is set
     */
    required: boolean;
};

export type ConfigDtoWritable = {
    /**
     * HCI device ID, e.g. hci0
     */
    bluetooth_adapter: string;
    display: DisplayDto;
    library: LibraryDto;
    /**
     * Logging verbosity; applied live
     */
    log_level: 'debug' | 'info' | 'warn' | 'error';
    mqtt: MqttDto;
    sensors: Array<SensorDto> | null;
    slideshow: SlideshowDto;
    updater: UpdaterDto;
    weather: WeatherDto;
};

export type ConfigMetaBodyWritable = {
    address_types: Array<string> | null;
    backends: Array<string> | null;
    /**
     * Decoder/parser names from the sensor registry
     */
    decoders: Array<string> | null;
    kinds: Array<string> | null;
    log_levels: Array<string> | null;
    sensor_types: Array<string> | null;
    units: Array<string> | null;
};

export type ConfigResponseBodyWritable = {
    /**
     * HCI device ID, e.g. hci0
     */
    bluetooth_adapter: string;
    display: DisplayDto;
    library: LibraryDto;
    /**
     * Logging verbosity; applied live
     */
    log_level: 'debug' | 'info' | 'warn' | 'error';
    mqtt: MqttDto;
    restart_pending: boolean;
    sensors: Array<SensorDto> | null;
    slideshow: SlideshowDto;
    updater: UpdaterDto;
    weather: WeatherDto;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type ImageFocusOutputBodyWritable = {
    detected: boolean;
    faces: Array<FaceBoxDto> | null;
};

export type ImageItemWritable = {
    /**
     * Image filename
     */
    name: string;
};

export type LibraryResponseWritable = {
    /**
     * Active library backend (fs or immich)
     */
    backend: string;
    /**
     * Sync status for remote backends
     */
    sync?: LibrarySync;
};

export type LoginRequestWritable = {
    password: string;
};

export type PutConfigResponseBodyWritable = {
    restart_pending: boolean;
};

export type ScreenStateResponseWritable = {
    /**
     * Whether automatic power management is active
     */
    auto: boolean;
    /**
     * Current screen power state
     */
    state: 'on' | 'off';
};

export type SetImageOrderInputBodyWritable = {
    /**
     * Apply the order to the running slideshow now (sent on Done)
     */
    commit?: boolean;
    /**
     * Full ordered list of image filenames
     */
    names: Array<string> | null;
};

export type SetPasswordRequestWritable = {
    /**
     * Current password; required when one is already set
     */
    current?: string;
    /**
     * New password; empty disables protection
     */
    new: string;
};

export type SetScreenRequestWritable = {
    /**
     * Desired screen power state
     */
    state: 'on' | 'off';
};

export type SystemDevicesBodyWritable = {
    /**
     * HCI device IDs, e.g. hci0
     */
    bluetooth_adapters: Array<string> | null;
    /**
     * Connected display connectors, e.g. HDMI-A-1
     */
    display_outputs: Array<string> | null;
    /**
     * true when the display backend can rotate and wlr-randr is installed
     */
    rotation_supported: boolean;
};

export type SystemInfoBodyWritable = {
    /**
     * Host power-off is permitted (polkit rule present)
     */
    canPowerOff: boolean;
    /**
     * Host reboot is permitted (polkit rule present)
     */
    canReboot: boolean;
    /**
     * CPU temperature in Celsius
     */
    cpuTempC?: number;
    /**
     * OS hostname
     */
    hostname: string;
    /**
     * Primary non-loopback IPv4, empty if none
     */
    ip: string;
    /**
     * Used memory percent
     */
    memUsedPct?: number;
    /**
     * Build target, e.g. linux_armv6
     */
    platform: string;
    /**
     * System uptime since boot as a Go duration
     */
    systemUptime?: string;
    /**
     * True if undervoltage detected
     */
    undervoltage?: boolean;
    /**
     * Process uptime as a Go duration, e.g. 3h12m0s
     */
    uptime: string;
    /**
     * Build version
     */
    version: string;
};

export type UpdateStatusResponseWritable = {
    /**
     * Whether a newer version is available
     */
    available: boolean;
    /**
     * Running version
     */
    current: string;
    /**
     * RFC3339 time of the last check
     */
    last_check?: string;
    /**
     * False when the last check couldn't reach the release source
     */
    last_check_ok: boolean;
    /**
     * Outcome of the last apply, e.g. 'rolled back from v1.2.0'
     */
    last_result?: string;
    /**
     * Bumps each time a result is recorded; lets the UI detect a repeated outcome
     */
    last_result_seq?: number;
    /**
     * Newest available version
     */
    latest?: string;
    /**
     * Release notes page for the newest version
     */
    notes_url?: string;
    /**
     * Current updater activity
     */
    phase: 'idle' | 'checking' | 'downloading' | 'verifying' | 'applying';
    /**
     * Build target, e.g. linux_armv6
     */
    platform: string;
};

export type WiFiConnectRequestWritable = {
    /**
     * Whether the network is hidden (non-broadcasting)
     */
    hidden?: boolean;
    /**
     * Network password
     */
    password?: string;
    /**
     * Network SSID to connect to
     */
    ssid: string;
};

export type WiFiStateWritable = {
    ap_enabled: boolean;
    ap_has_password: boolean;
    ap_ssid: string;
    hostname: string;
    ip: string;
    last_connect_error?: string;
    last_connect_ssid?: string;
    mode: string;
    security: string;
    signal: number;
    ssid: string;
};

export type AuthLoginData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthSetPasswordData = {
    body: SetPasswordRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/password';
};

export type AuthSetPasswordErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthSetPasswordError = AuthSetPasswordErrors[keyof AuthSetPasswordErrors];

export type AuthSetPasswordResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthSetPasswordResponse = AuthSetPasswordResponses[keyof AuthSetPasswordResponses];

export type AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/status';
};

export type AuthStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthStatusError = AuthStatusErrors[keyof AuthStatusErrors];

export type AuthStatusResponses = {
    /**
     * OK
     */
    200: AuthStatusResponse;
};

export type AuthStatusResponse2 = AuthStatusResponses[keyof AuthStatusResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * OK
     */
    200: ConfigResponseBody;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type PutConfigData = {
    body: ConfigDtoWritable;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type PutConfigErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutConfigError = PutConfigErrors[keyof PutConfigErrors];

export type PutConfigResponses = {
    /**
     * OK
     */
    200: PutConfigResponseBody;
};

export type PutConfigResponse = PutConfigResponses[keyof PutConfigResponses];

export type GetConfigMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config/meta';
};

export type GetConfigMetaErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetConfigMetaError = GetConfigMetaErrors[keyof GetConfigMetaErrors];

export type GetConfigMetaResponses = {
    /**
     * OK
     */
    200: ConfigMetaBody;
};

export type GetConfigMetaResponse = GetConfigMetaResponses[keyof GetConfigMetaResponses];

export type HeartbeatData = {
    body?: never;
    path?: never;
    query?: {
        version?: string;
        aspect?: number;
    };
    url: '/api/heartbeat';
};

export type HeartbeatErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HeartbeatError = HeartbeatErrors[keyof HeartbeatErrors];

export type HeartbeatResponses = {
    /**
     * No Content
     */
    204: void;
};

export type HeartbeatResponse = HeartbeatResponses[keyof HeartbeatResponses];

export type ListImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/images';
};

export type ListImagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListImagesError = ListImagesErrors[keyof ListImagesErrors];

export type ListImagesResponses = {
    /**
     * OK
     */
    200: Array<ImageItem> | null;
};

export type ListImagesResponse = ListImagesResponses[keyof ListImagesResponses];

export type UploadImageData = {
    body?: {
        image: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/images';
};

export type UploadImageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UploadImageError = UploadImageErrors[keyof UploadImageErrors];

export type UploadImageResponses = {
    /**
     * Created
     */
    201: ImageItem;
};

export type UploadImageResponse = UploadImageResponses[keyof UploadImageResponses];

export type SetImageOrderData = {
    body: SetImageOrderInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/images/order';
};

export type SetImageOrderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SetImageOrderError = SetImageOrderErrors[keyof SetImageOrderErrors];

export type SetImageOrderResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetImageOrderResponse = SetImageOrderResponses[keyof SetImageOrderResponses];

export type DeleteImageData = {
    body?: never;
    path: {
        /**
         * Image filename
         */
        name: string;
    };
    query?: never;
    url: '/api/images/{name}';
};

export type DeleteImageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteImageError = DeleteImageErrors[keyof DeleteImageErrors];

export type DeleteImageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteImageResponse = DeleteImageResponses[keyof DeleteImageResponses];

export type GetLibraryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/library';
};

export type GetLibraryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLibraryError = GetLibraryErrors[keyof GetLibraryErrors];

export type GetLibraryResponses = {
    /**
     * OK
     */
    200: LibraryResponse;
};

export type GetLibraryResponse = GetLibraryResponses[keyof GetLibraryResponses];

export type SyncLibraryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/library/sync';
};

export type SyncLibraryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SyncLibraryError = SyncLibraryErrors[keyof SyncLibraryErrors];

export type SyncLibraryResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetScreenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/screen';
};

export type GetScreenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetScreenError = GetScreenErrors[keyof GetScreenErrors];

export type GetScreenResponses = {
    /**
     * OK
     */
    200: ScreenStateResponse;
};

export type GetScreenResponse = GetScreenResponses[keyof GetScreenResponses];

export type SetScreenData = {
    body: SetScreenRequestWritable;
    path?: never;
    query?: never;
    url: '/api/screen';
};

export type SetScreenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SetScreenError = SetScreenErrors[keyof SetScreenErrors];

export type SetScreenResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetScreenResponse = SetScreenResponses[keyof SetScreenResponses];

export type ScreenWakeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/screen/wake';
};

export type ScreenWakeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ScreenWakeError = ScreenWakeErrors[keyof ScreenWakeErrors];

export type ScreenWakeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ScreenWakeResponse = ScreenWakeResponses[keyof ScreenWakeResponses];

export type SlideshowNextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/slideshow/next';
};

export type SlideshowNextErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SlideshowNextError = SlideshowNextErrors[keyof SlideshowNextErrors];

export type SlideshowNextResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SlideshowNextResponse = SlideshowNextResponses[keyof SlideshowNextResponses];

export type SlideshowPrevData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/slideshow/prev';
};

export type SlideshowPrevErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SlideshowPrevError = SlideshowPrevErrors[keyof SlideshowPrevErrors];

export type SlideshowPrevResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SlideshowPrevResponse = SlideshowPrevResponses[keyof SlideshowPrevResponses];

export type GetSystemDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/devices';
};

export type GetSystemDevicesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSystemDevicesError = GetSystemDevicesErrors[keyof GetSystemDevicesErrors];

export type GetSystemDevicesResponses = {
    /**
     * OK
     */
    200: SystemDevicesBody;
};

export type GetSystemDevicesResponse = GetSystemDevicesResponses[keyof GetSystemDevicesResponses];

export type GetSystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/info';
};

export type GetSystemInfoErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSystemInfoError = GetSystemInfoErrors[keyof GetSystemInfoErrors];

export type GetSystemInfoResponses = {
    /**
     * OK
     */
    200: SystemInfoBody;
};

export type GetSystemInfoResponse = GetSystemInfoResponses[keyof GetSystemInfoResponses];

export type GetLicensesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/licenses';
};

export type GetLicensesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLicensesError = GetLicensesErrors[keyof GetLicensesErrors];

export type GetLicensesResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetLicensesResponse = GetLicensesResponses[keyof GetLicensesResponses];

export type SystemRebootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/reboot';
};

export type SystemRebootErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SystemRebootError = SystemRebootErrors[keyof SystemRebootErrors];

export type SystemRebootResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type SystemRestartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/restart';
};

export type SystemRestartErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SystemRestartError = SystemRestartErrors[keyof SystemRestartErrors];

export type SystemRestartResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type SystemShutdownData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/shutdown';
};

export type SystemShutdownErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SystemShutdownError = SystemShutdownErrors[keyof SystemShutdownErrors];

export type SystemShutdownResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update';
};

export type GetUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUpdateError = GetUpdateErrors[keyof GetUpdateErrors];

export type GetUpdateResponses = {
    /**
     * OK
     */
    200: UpdateStatusResponse;
};

export type GetUpdateResponse = GetUpdateResponses[keyof GetUpdateResponses];

export type ApplyUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update';
};

export type ApplyUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyUpdateError = ApplyUpdateErrors[keyof ApplyUpdateErrors];

export type ApplyUpdateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type CheckUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/update/check';
};

export type CheckUpdateErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CheckUpdateError = CheckUpdateErrors[keyof CheckUpdateErrors];

export type CheckUpdateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type ConfigureApData = {
    body: ApRequestWritable;
    path?: never;
    query?: never;
    url: '/api/wifi/ap';
};

export type ConfigureApErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ConfigureApError = ConfigureApErrors[keyof ConfigureApErrors];

export type ConfigureApResponses = {
    /**
     * OK
     */
    200: WiFiState;
};

export type ConfigureApResponse = ConfigureApResponses[keyof ConfigureApResponses];

export type WifiConnectData = {
    body: WiFiConnectRequestWritable;
    path?: never;
    query?: never;
    url: '/api/wifi/connect';
};

export type WifiConnectErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WifiConnectError = WifiConnectErrors[keyof WifiConnectErrors];

export type WifiConnectResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type WifiForgetData = {
    body?: never;
    path: {
        /**
         * Network SSID to forget
         */
        ssid: string;
    };
    query?: never;
    url: '/api/wifi/network/{ssid}';
};

export type WifiForgetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type WifiForgetError = WifiForgetErrors[keyof WifiForgetErrors];

export type WifiForgetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type WifiForgetResponse = WifiForgetResponses[keyof WifiForgetResponses];

export type GetWifiNetworksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wifi/networks';
};

export type GetWifiNetworksErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetWifiNetworksError = GetWifiNetworksErrors[keyof GetWifiNetworksErrors];

export type GetWifiNetworksResponses = {
    /**
     * OK
     */
    200: Array<WiFiNetwork> | null;
};

export type GetWifiNetworksResponse = GetWifiNetworksResponses[keyof GetWifiNetworksResponses];

export type GetWifiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wifi/status';
};

export type GetWifiStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetWifiStatusError = GetWifiStatusErrors[keyof GetWifiStatusErrors];

export type GetWifiStatusResponses = {
    /**
     * OK
     */
    200: WiFiState;
};

export type GetWifiStatusResponse = GetWifiStatusResponses[keyof GetWifiStatusResponses];

export type EventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events';
};

export type EventsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EventsError = EventsErrors[keyof EventsErrors];

export type EventsResponses = {
    /**
     * Server Sent Events
     *
     * Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.
     */
    200: Array<{
        data: ImagePayload;
        /**
         * The event name.
         */
        event: 'image';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: KioskPayload;
        /**
         * The event name.
         */
        event: 'kiosk';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: PingEvent;
        /**
         * The event name.
         */
        event: 'ping';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: ReadyEvent;
        /**
         * The event name.
         */
        event: 'ready';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: ScreenPayload;
        /**
         * The event name.
         */
        event: 'screen';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: ScreenAspectPayload;
        /**
         * The event name.
         */
        event: 'screen_aspect';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: SensorPayload;
        /**
         * The event name.
         */
        event: 'sensor';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: TouchPayload;
        /**
         * The event name.
         */
        event: 'touch';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: WeatherPayload;
        /**
         * The event name.
         */
        event: 'weather';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    }>;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthzError = HealthzErrors[keyof HealthzErrors];

export type HealthzResponses = {
    /**
     * No Content
     */
    204: void;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ServeImageData = {
    body?: never;
    path: {
        /**
         * Image filename
         */
        name: string;
    };
    query?: never;
    url: '/img/{name}';
};

export type ServeImageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ServeImageError = ServeImageErrors[keyof ServeImageErrors];

export type ServeImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ImageFocusData = {
    body?: never;
    path: {
        /**
         * Image filename
         */
        name: string;
    };
    query?: never;
    url: '/img/{name}/focus';
};

export type ImageFocusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ImageFocusError = ImageFocusErrors[keyof ImageFocusErrors];

export type ImageFocusResponses = {
    /**
     * OK
     */
    200: ImageFocusOutputBody;
};

export type ImageFocusResponse = ImageFocusResponses[keyof ImageFocusResponses];
